server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset : UTF-8
      enabled: true
      force: true

spring:
  cloud:
    aws:
      credentials:
        access-key: ${spring.cloud.aws.credentials.access-key} # AWS IAM의 Access Key
        secret-key: ${spring.cloud.aws.credentials.secret-key}  # AWS IAM의 Secret Key
      region:
        static: ap-southeast-2 # 예: ap-northeast-2
      s3:
        bucket: spring-plus-bucket # S3 버킷 이름


  application:
    name: Spring26
  datasource:
    url: jdbc:mysql://localhost:3306/springplus
    username: root
    password:

    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.MySQL8Dialect

jwt:
  secret.key: 7Iqk7YyM66W07YOA7L2U65Sp7YG065+9U3ByaW5n6rCV7J2Y7Yqc7YSw7LWc7JuQ67mI7J6F64uI64ukLg==


